<a href="https://colab.research.google.com/github/sihyun10/TextMining_class/blob/main/%5B1%5D_%EB%8D%B0%EC%9D%B4%ED%84%B0_%EC%82%AC%EC%A0%84%EC%B2%98%EB%A6%AC%EB%A5%BC_%EC%9C%84%ED%95%9C_%EA%B8%B0%EC%B4%88_%ED%8C%8C%EC%9D%B4%EC%8D%AC_%EC%BD%94%EB%94%A9.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
#pandas 라이브러리
#파이썬을 이용하여 데이터 분석을 할 때 가장 많이 사용하는 라이브러리

#pandas 기능들
#결측치 처리, 열(필드)의 삽입과 제거, 데이터 정렬 및 병합, 타 자료구조를 pandas 데이터프레임 형태로 변환
#색인, 인덱싱, 부분집합/ 데이터 셋 조인 및 차원 변환, 축의 계층적 라벨링(Labeling)
#다양한 포맷으로의 입출력 가능과 시계열 함수

In [2]:
#pandas 자료구조
#Series : 일련의 객체를 담을 수 있는 1차원의 배열과 같은 자료구조.

import pandas as pd
obj = pd.Series([4,7,-5,3])
obj

0    4
1    7
2   -5
3    3
dtype: int64

**Series 객체의 문자열 표현**

*   왼쪽 : 색인
*   오른쪽 : 색인의 해당하는 값

*   데이터에 색인을 지정하지 않으면, 기본 색인인 정수 0에서 
데이터의 길이 -1까지의 숫자가 표현됨.
*   Series의 값과 색인은 values와 index 속성을 통해 얻거나 지정할 수 있음.





In [3]:
#Series : values와 index 속성 확인.

obj.values

array([ 4,  7, -5,  3])

In [4]:
obj.index

RangeIndex(start=0, stop=4, step=1)

In [5]:
obj2 = pd.Series([172,173,167,180], index=['안유진','장원영','카리나','문지훈'])

In [6]:
obj2

안유진    172
장원영    173
카리나    167
문지훈    180
dtype: int64

In [7]:
#Seires : 값을 선택하거나 대입할 때 색인을 통해 접근
obj2['문지훈']

180

In [8]:
obj2['문지훈'] = 179

In [9]:
obj2[['안유진','장원영','문지훈']]

안유진    172
장원영    173
문지훈    179
dtype: int64

In [10]:
#Series : 누락된 값을 찾을 때도 적용
obj2.isnull()

안유진    False
장원영    False
카리나    False
문지훈    False
dtype: bool

In [11]:
#DataFrame
data={'Member':['태연','써니','티파니','윤아','문지훈'],
      'Year':[1989,1989,1989,1990,1989]}

In [12]:
frame=pd.DataFrame(data)

In [13]:
frame

Member  Year
0     태연  1989
1     써니  1989
2    티파니  1989
3     윤아  1990
4    문지훈  1989

In [14]:
#DataFrame : 원하는 순서대로 열을 지정하면 원하는 순서를 지닌 DataFrame 객체가 새성.

frame2= pd.DataFrame(data, columns = ['Year','Member'])

In [15]:
frame2

Year Member
0  1989     태연
1  1989     써니
2  1989    티파니
3  1990     윤아
4  1989    문지훈

In [16]:
#DataFrame : 열은 사전 형식의 표기법으로 접근할 수 있음.
frame2['Member']

0     태연
1     써니
2    티파니
3     윤아
4    문지훈
Name: Member, dtype: object

In [17]:
#DataFrmae : 열과 마찬가지로 행에도 색인을 넣을 수 있음.
frame3 = pd.DataFrame(data,index=['One','Two','Three','Four','Five'])

In [18]:
frame3

Member  Year
One       태연  1989
Two       써니  1989
Three    티파니  1989
Four      윤아  1990
Five     문지훈  1989

In [19]:
#DataFrame : 행렬 전치(Transpose)도 쉽게 수행할 수 있음.
frame3.T

One   Two Three  Four  Five
Member    태연    써니   티파니    윤아   문지훈
Year    1989  1989  1989  1990  1989

In [20]:
#DataFrame : drop을 통해 선택한 값이 삭제된 객체를 얻을 수 있음.
frame3.drop(['Five'])

Member  Year
One       태연  1989
Two       써니  1989
Three    티파니  1989
Four      윤아  1990

In [21]:
frame3.drop('Year',axis=1)

Member
One       태연
Two       써니
Three    티파니
Four      윤아
Five     문지훈

In [22]:
#DataFrame : 행이나 칼럼의 색인을 알파벳 순으로 정렬하거나 데이터값을 크기에 따라 정렬할 수 있음.
frame4 = pd.DataFrame([[1,3,2,5],[4,2,6,1]],index=['Three','One',],
                      columns=['d','a','b','c'])

In [23]:
frame4

d  a  b  c
Three  1  3  2  5
One    4  2  6  1

In [24]:
frame4.sort_index()

d  a  b  c
One    4  2  6  1
Three  1  3  2  5

In [25]:
frame4.sort_index(axis=1)

a  b  c  d
Three  3  2  5  1
One    2  6  1  4

In [26]:
#DataFrame : 정렬은 기본적으로 오름차순으로 되어있지만, 내림차순으로도 정렬할 수 있음.
frame4.sort_index(axis=1,ascending=False)

d  c  b  a
Three  1  5  2  3
One    4  1  6  2

In [27]:
#DataFrame : 특정 열의 값에 따라 행들을 정렬할 수 있음.
frame4.sort_values(by=['c'])

d  a  b  c
One    4  2  6  1
Three  1  3  2  5

**numpy 라이브러리**

In [28]:
#numpy 다차원 배열 객체 : ndarray
#numpy의 핵심 기능 중 하나인 다차원 배열 객체
#파이썬에서 대규모 데이터 집합을 담을 수 있는 빠르고 유연한 자료구조

import numpy as np

In [29]:
data = np.random.randn(2,3)

In [30]:
data

array([[ 0.63790728, -0.01995502,  0.97966633],
       [-0.7616028 , -0.54098475, -1.46323786]])

In [31]:
#ndarray : 자유로운 사칙연산이 가능

data*2

array([[ 1.27581455, -0.03991005,  1.95933265],
       [-1.52320561, -1.0819695 , -2.92647571]])

In [32]:
data+data+data

array([[ 1.91372183, -0.05986507,  2.93899898],
       [-2.28480841, -1.62295425, -4.38971357]])

In [33]:
#shape : 배열의 차원 크기를 확인할 수 있음.
data.shape

(2, 3)

In [34]:
data.dtype

dtype('float64')

In [35]:
#zeros와 ones : 주어진 길이나 모양에 각각 0과 1이 들어있는 배열 생성

np.zeros((3,6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [36]:
np.ones((3,6))

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [37]:
#numpy : 색인을 통해 데이터값에 접근할 수 있음
arr = np.arange(10)

In [38]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [39]:
arr[5]

5

In [40]:
arr[5:8]

array([5, 6, 7])

In [51]:
#numpy : 다차원 배열에서도 색인을 통해 데이터값에 접근할 수 있음.

arr2d = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [52]:
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [42]:
arr2d[1]

array([4, 5, 6])

In [43]:
arr2d[1][0]

4

In [44]:
arr2d[1,0]

4

In [45]:
#마지막 색인을 생략하면 반환되는 객체는 상위 차원의 데이터를 포함하고 있는 한 차원 낮은 ndarray가 생성됨.

arr3d = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])

In [46]:
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [47]:
arr3d[0]

array([[1, 2, 3],
       [4, 5, 6]])

In [54]:
#numpy 다차원 배열 객체
#슬라이스 색인

arr2d = arr2d[:2,1:]

In [55]:
arr2d

array([[2, 3],
       [5, 6]])